name: marg_mitra
description: "Emergency and roadside assistance app for travelers"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9  # Changed to stable version
  go_router: ^16.1.0
  freezed_annotation: ^3.1.0

  # Location & Maps

  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  location: ^8.0.1


  # HTTP & API
  http: ^1.5.0
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

  # Notifications
  flutter_local_notifications: ^19.4.0

  # Authentication & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.6


  # Phone Authentication
  country_code_picker: ^3.3.0
  pin_code_fields: ^8.0.1

  # Image & File Handling
  image_picker:   ^1.0.4
  cached_network_image: ^3.4.1

  # Permissions
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

  # Utils
  intl: 0.19.0
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.5

  # Payment Integration
  razorpay_flutter: ^1.4.0

  device_info_plus: ^12.1.0
  flutter_contacts: ^1.1.7+1
  # UI Components
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  syncfusion_flutter_charts: 31.2.2
  flutter_blue_plus: ^1.32.0
  sensors_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  workmanager: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_analytics: ^10.8.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_logo.png"
